package interfaz;

import java.util.ArrayList;
import utilidades.Consola;
import logica.Fachada;
import logica.Promocion;
import logica.Producto;
import logica.InfoProducto;

public class DialogoReportePromocion extends javax.swing.JDialog {
    
    Fachada logica = Fachada.getInstancia();
    
    public DialogoReportePromocion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        actualizarListaPromociones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        verReporteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        promocionesList = new javax.swing.JList<>();
        Cancelar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Obligatorio 1 - MDA");
        setLocation(new java.awt.Point(710, 390));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));

        jLabel4.setText("Seleccione promocion:");

        verReporteButton.setText("Ver Reporte");
        verReporteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verReporteButtonActionPerformed(evt);
            }
        });

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane2.setViewportView(outputTextArea);

        promocionesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(promocionesList);

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(verReporteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verReporteButton)
                    .addComponent(Cancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verReporteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verReporteButtonActionPerformed
        Consola.logMsg("Ver Reporte clicked!");
        actualizarReporteDePromociones();
        //this.cancelar();
    }//GEN-LAST:event_verReporteButtonActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        Consola.logMsg("Cancelar clicked!");
        this.cancelar();
    }//GEN-LAST:event_CancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JList<String> promocionesList;
    private javax.swing.JButton verReporteButton;
    // End of variables declaration//GEN-END:variables

    private void cancelar() {
        this.dispose();
    }
    
    public void actualizarListaPromociones() {
        ArrayList <Promocion> promos =  logica.getPromociones();
        if(promos.isEmpty()){
            outputTextArea.setText("No existen promociones ingresadas.");
            return;
        }
        
        ArrayList <String> nombresPromos;
        nombresPromos = new ArrayList();
        for(Promocion p:promos){
            nombresPromos.add(p.getNombre());
        }
        promocionesList.setListData(nombresPromos.toArray(String[]::new));
    }
    
    
    public void actualizarReporteDePromociones() {
        ArrayList <Promocion> promos =  logica.getPromociones();
        if(promos.isEmpty()){
            outputTextArea.setText("No existen promociones ingresadas.");
            return;
        }

        Promocion selectedPromo = promos.get(promocionesList.getSelectedIndex());
        ArrayList <String> lineasReporte = new ArrayList();

        lineasReporte.add("Codigo: " + selectedPromo.getCodigo()  + " - Nombre: " + selectedPromo.getNombre() + " - Descuento: "  + selectedPromo.getDescuento() + "%");
        float montoTotal = logica.montoDeDescuentoOtorgadoPorPromocion(selectedPromo.getCodigo());

        lineasReporte.add("Monto total de descuento otorgado: " + montoTotal);
        lineasReporte.add("Lista de productos incluidos: ");
        
        ArrayList <Producto> productosEnPromo = selectedPromo.getProductos();
        
        for (Producto p:productosEnPromo){
            String lineaProducto = new String();
            InfoProducto info = logica.InformacionPorProducto(p);
            lineaProducto =     "N: " + info.getNombre() + 
                                " - P: "  + info.getPrecioDeLista() + 
                                " - F: " + info.getCantidadDeFacturas() +
                                " - U: " + info.getCantidadDeUnidadesVenidas() +
                                " - M: " + info.getMontoTotalDescuento();
            
            lineasReporte.add(lineaProducto);
        }
               
        outputTextArea.setText(Stringify(lineasReporte));
    }
    
    private String Stringify(ArrayList <String> lineas){
        String result = new String();
        for (String s:lineas){
            result = result.concat(s + "\n");
        }
        return result;
    }
    
}
